skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
agacy_policy_v2 = "783Eojkn9uMHtNCiM6yiTecRrdddFM7xEiwBu7Sxxm1G"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
