"use client";

import { useState } from "react";
import {
  SCENARIO,
  ciphertextPreview,
  formatTokens,
  runScenario,
} from "../server/services/demo-scenario";

const scenario = runScenario();

export default function Home() {
  const [step, setStep] = useState(0);
  const [ownerView, setOwnerView] = useState(false);

  const visible = step;
  const canAdvance = step < SCENARIO.length;

  return (
    <>
      <header className="hero">
        <div className="wrap">
          <p className="eyebrow">Agacy — Agentic Privacy</p>
          <h1>
            Your AI agent spends on-chain.
            <br />
            Everyone can read <em>exactly</em> how much.
          </h1>
          <p className="lede">
            2.3 million AI agents already hold wallets and transact on their own. Every amount,
            every balance, every counterparty is permanently public — and attackers now pick
            targets by reading balances. Agacy runs an agent&apos;s payments through Solana&apos;s
            confidential transfers: the transaction is provably valid, the amount is unreadable.
          </p>

          <div className="stats">
            <div>
              <div className="stat-value">2.3M</div>
              <div className="stat-label">AI agents transacting on-chain today</div>
            </div>
            <div>
              <div className="stat-value">165M</div>
              <div className="stat-label">agent payments processed via x402</div>
            </div>
            <div>
              <div className="stat-value">+207%</div>
              <div className="stat-label">
                jump in phishing losses as attackers shifted to targeting visible balances
              </div>
            </div>
          </div>
        </div>
      </header>

      <main className="wrap sim">
        <div className="section-head">
          <h2>Same agent. Same payments. Different exposure.</h2>
          <p className="section-sub">
            An agent managing a stablecoin budget makes three routine payments over a week. On the
            left it uses ordinary public rails. On the right it uses Agacy. Step through and watch
            what a stranger with a block explorer can learn.
          </p>
        </div>

        <div className="controls">
          <button className="primary" onClick={() => setStep(step + 1)} disabled={!canAdvance}>
            {step === 0 ? "Run agent" : canAdvance ? "Next payment" : "Done"}
          </button>
          <button onClick={() => { setStep(0); setOwnerView(false); }} disabled={step === 0}>
            Reset
          </button>
          <button onClick={() => setOwnerView(!ownerView)} disabled={step === 0}>
            {ownerView ? "Hide owner view" : "View as owner"}
          </button>
          <span className="hint">
            {step === 0
              ? "Nothing has happened yet."
              : `${visible} of ${SCENARIO.length} payments made`}
          </span>
        </div>

        <div className="panels">
          <ExposedPanel count={visible} />
          <ConfidentialPanel count={visible} ownerView={ownerView} />
        </div>
      </main>

      <footer className="foot">
        <div className="wrap">
          Built on Solana&apos;s native Token-2022 confidential transfers. The public column here is
          generated by the same <code>toPublicView</code> boundary the production code uses, so it
          cannot display a field the real public view would not have.
        </div>
      </footer>
    </>
  );
}

function ExposedPanel({ count }: { count: number }) {
  const rows = scenario.exposed.slice(0, count);
  const latest = rows.at(-1);

  return (
    <section className="panel">
      <div className="panel-head">
        <div>
          <div className="panel-title">Agent without Agacy</div>
          <div className="panel-note">Ordinary SPL transfers</div>
        </div>
        <span className="tag exposed">Fully public</span>
      </div>

      <div className="explorer">
        <div className="explorer-label">What a stranger sees on the explorer</div>

        {rows.length === 0 ? (
          <p className="empty">No transactions yet.</p>
        ) : (
          <>
            {rows.map((tx, i) => (
              <div key={tx.signature}>
                <div className="row">
                  <span className="row-key">Payment {i + 1}</span>
                  <span className="row-val exposed">{formatTokens(tx.amount)} USDC</span>
                </div>
                <div className="row">
                  <span className="row-key">To</span>
                  <span className="row-val exposed">{tx.counterparty.slice(0, 18)}…</span>
                </div>
              </div>
            ))}
            {latest && (
              <div className="row">
                <span className="row-key">Balance after</span>
                <span className="row-val exposed">{formatTokens(latest.resultingBalance)} USDC</span>
              </div>
            )}
            <div className="verdict exposed">
              A stranger now knows this wallet holds{" "}
              <strong>{latest ? formatTokens(latest.resultingBalance) : "—"} USDC</strong>, what it
              buys, and who it pays. That is the shortlist attackers work from.
            </div>
          </>
        )}
      </div>
    </section>
  );
}

function ConfidentialPanel({ count, ownerView }: { count: number; ownerView: boolean }) {
  const publicRows = scenario.publicView.slice(0, count);
  const authorizedRows = scenario.authorized.slice(0, count);
  const latest = authorizedRows.at(-1);

  return (
    <section className="panel">
      <div className="panel-head">
        <div>
          <div className="panel-title">Agent with Agacy</div>
          <div className="panel-note">Token-2022 confidential transfers</div>
        </div>
        <span className="tag private">Encrypted</span>
      </div>

      <div className="explorer">
        <div className="explorer-label">What the same stranger sees</div>

        {publicRows.length === 0 ? (
          <p className="empty">No transactions yet.</p>
        ) : (
          <>
            {publicRows.map((tx, i) => (
              <div key={tx.signature}>
                <div className="row">
                  <span className="row-key">Payment {i + 1}</span>
                  <span className="row-val hidden">confirmed · amount encrypted</span>
                </div>
                <div className="cipher">{ciphertextPreview(authorizedRows[i]!.amount, i)}</div>
              </div>
            ))}
            <div className="row">
              <span className="row-key">Balance after</span>
              <span className="row-val hidden">unreadable</span>
            </div>
            <div className="verdict private">
              The transactions are real, confirmed, and verifiable — the chain proved each one was
              valid without ever learning the amount. There is no balance here to target.
            </div>
          </>
        )}
      </div>

      {ownerView && latest && (
        <div className="owner-view">
          <div className="owner-head">Decrypted with the owner&apos;s key</div>
          {authorizedRows.map((tx, i) => (
            <div className="row" key={tx.signature}>
              <span className="row-key">Payment {i + 1}</span>
              <span className="row-val">{formatTokens(tx.amount)} USDC</span>
            </div>
          ))}
          <div className="row">
            <span className="row-key">Balance</span>
            <span className="row-val">{formatTokens(latest.resultingBalance)} USDC</span>
          </div>
          <div className="row">
            <span className="row-key">Agent said</span>
            <span className="row-val" style={{ fontFamily: "var(--sans)", textAlign: "left" }}>
              {latest.agentReasoning}
            </span>
          </div>
        </div>
      )}
    </section>
  );
}
